import {
  adoptCat,
  ADOPT_CAT_ERROR,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  fetchCat,
  FETCH_CAT_ERROR,
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS
} from './cat';

import {
  adoptDog,
  ADOPT_DOG_ERROR,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  fetchDog,
  FETCH_DOG_ERROR,
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS
} from './dog';

export {
  adoptCat,
  ADOPT_CAT_ERROR,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  fetchCat,
  FETCH_CAT_ERROR,
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
  adoptDog,
  ADOPT_DOG_ERROR,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  fetchDog,
  FETCH_DOG_ERROR,
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS
};
