import {
  FETCH_CATS_REQUEST, 
  FETCH_CATS_SUCCESS, 
  FETCH_CATS_ERROR,
  ADOPT_CATS_REQUEST,
  ADOPT_CATS_SUCCESS,
  ADOPT_CATS_ERROR,
} from './cats';

import {FETCH_DOGS_REQUEST,
  FETCH_DOGS_SUCCESS,
  FETCH_DOGS_ERROR,
  ADOPT_DOGS_REQUEST,
  ADOPT_DOGS_SUCCESS,
  ADOPT_DOGS_ERROR } from './dogs';

export const cats = {
    FETCH_CATS_REQUEST,
    FETCH_CATS_SUCCESS,
    FETCH_CATS_ERROR,
    ADOPT_CATS_REQUEST,
    ADOPT_CATS_SUCCESS,
    ADOPT_CATS_ERROR,
  };

export const dogs = {
  FETCH_DOGS_REQUEST,
  FETCH_DOGS_SUCCESS,
  FETCH_DOGS_ERROR,
  ADOPT_DOGS_REQUEST,
  ADOPT_DOGS_SUCCESS,
  ADOPT_DOGS_ERROR };
